//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalCShar.ServiceConsult {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.slin.com.pe/", ConfigurationName="ServiceConsult.WServiceGetDocumentSoap")]
    public interface WServiceGetDocumentSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NUM_CPE del espacio de nombres http://www.slin.com.pe/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetDocumentoPDF", ReplyAction="*")]
        PortalCShar.ServiceConsult.GetDocumentoPDFResponse GetDocumentoPDF(PortalCShar.ServiceConsult.GetDocumentoPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetDocumentoPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetDocumentoPDFResponse> GetDocumentoPDFAsync(PortalCShar.ServiceConsult.GetDocumentoPDFRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NUM_CPE del espacio de nombres http://www.slin.com.pe/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetDocumentoXML", ReplyAction="*")]
        PortalCShar.ServiceConsult.GetDocumentoXMLResponse GetDocumentoXML(PortalCShar.ServiceConsult.GetDocumentoXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetDocumentoXML", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetDocumentoXMLResponse> GetDocumentoXMLAsync(PortalCShar.ServiceConsult.GetDocumentoXMLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NUM_CE del espacio de nombres http://www.slin.com.pe/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetStatusDocument", ReplyAction="*")]
        PortalCShar.ServiceConsult.GetStatusDocumentResponse GetStatusDocument(PortalCShar.ServiceConsult.GetStatusDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetStatusDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetStatusDocumentResponse> GetStatusDocumentAsync(PortalCShar.ServiceConsult.GetStatusDocumentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NUM_CE del espacio de nombres http://www.slin.com.pe/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetStatusDocuments", ReplyAction="*")]
        PortalCShar.ServiceConsult.GetStatusDocumentsResponse GetStatusDocuments(PortalCShar.ServiceConsult.GetStatusDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetStatusDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetStatusDocumentsResponse> GetStatusDocumentsAsync(PortalCShar.ServiceConsult.GetStatusDocumentsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento param del espacio de nombres http://www.slin.com.pe/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/CancelDocument", ReplyAction="*")]
        PortalCShar.ServiceConsult.CancelDocumentResponse CancelDocument(PortalCShar.ServiceConsult.CancelDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/CancelDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.CancelDocumentResponse> CancelDocumentAsync(PortalCShar.ServiceConsult.CancelDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentoPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentoPDF", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.GetDocumentoPDFRequestBody Body;
        
        public GetDocumentoPDFRequest() {
        }
        
        public GetDocumentoPDFRequest(PortalCShar.ServiceConsult.GetDocumentoPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetDocumentoPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NUM_CPE;
        
        public GetDocumentoPDFRequestBody() {
        }
        
        public GetDocumentoPDFRequestBody(string NUM_CPE) {
            this.NUM_CPE = NUM_CPE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentoPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentoPDFResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.GetDocumentoPDFResponseBody Body;
        
        public GetDocumentoPDFResponse() {
        }
        
        public GetDocumentoPDFResponse(PortalCShar.ServiceConsult.GetDocumentoPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetDocumentoPDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDocumentoPDFResult;
        
        public GetDocumentoPDFResponseBody() {
        }
        
        public GetDocumentoPDFResponseBody(string GetDocumentoPDFResult) {
            this.GetDocumentoPDFResult = GetDocumentoPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentoXML", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.GetDocumentoXMLRequestBody Body;
        
        public GetDocumentoXMLRequest() {
        }
        
        public GetDocumentoXMLRequest(PortalCShar.ServiceConsult.GetDocumentoXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetDocumentoXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NUM_CPE;
        
        public GetDocumentoXMLRequestBody() {
        }
        
        public GetDocumentoXMLRequestBody(string NUM_CPE) {
            this.NUM_CPE = NUM_CPE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentoXMLResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.GetDocumentoXMLResponseBody Body;
        
        public GetDocumentoXMLResponse() {
        }
        
        public GetDocumentoXMLResponse(PortalCShar.ServiceConsult.GetDocumentoXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetDocumentoXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDocumentoXMLResult;
        
        public GetDocumentoXMLResponseBody() {
        }
        
        public GetDocumentoXMLResponseBody(string GetDocumentoXMLResult) {
            this.GetDocumentoXMLResult = GetDocumentoXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusDocument", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.GetStatusDocumentRequestBody Body;
        
        public GetStatusDocumentRequest() {
        }
        
        public GetStatusDocumentRequest(PortalCShar.ServiceConsult.GetStatusDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetStatusDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NUM_CE;
        
        public GetStatusDocumentRequestBody() {
        }
        
        public GetStatusDocumentRequestBody(string NUM_CE) {
            this.NUM_CE = NUM_CE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusDocumentResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.GetStatusDocumentResponseBody Body;
        
        public GetStatusDocumentResponse() {
        }
        
        public GetStatusDocumentResponse(PortalCShar.ServiceConsult.GetStatusDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetStatusDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStatusDocumentResult;
        
        public GetStatusDocumentResponseBody() {
        }
        
        public GetStatusDocumentResponseBody(string GetStatusDocumentResult) {
            this.GetStatusDocumentResult = GetStatusDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusDocuments", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.GetStatusDocumentsRequestBody Body;
        
        public GetStatusDocumentsRequest() {
        }
        
        public GetStatusDocumentsRequest(PortalCShar.ServiceConsult.GetStatusDocumentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetStatusDocumentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NUM_CE;
        
        public GetStatusDocumentsRequestBody() {
        }
        
        public GetStatusDocumentsRequestBody(string NUM_CE) {
            this.NUM_CE = NUM_CE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusDocumentsResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.GetStatusDocumentsResponseBody Body;
        
        public GetStatusDocumentsResponse() {
        }
        
        public GetStatusDocumentsResponse(PortalCShar.ServiceConsult.GetStatusDocumentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetStatusDocumentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStatusDocumentsResult;
        
        public GetStatusDocumentsResponseBody() {
        }
        
        public GetStatusDocumentsResponseBody(string GetStatusDocumentsResult) {
            this.GetStatusDocumentsResult = GetStatusDocumentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelDocument", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.CancelDocumentRequestBody Body;
        
        public CancelDocumentRequest() {
        }
        
        public CancelDocumentRequest(PortalCShar.ServiceConsult.CancelDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class CancelDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param;
        
        public CancelDocumentRequestBody() {
        }
        
        public CancelDocumentRequestBody(string param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelDocumentResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public PortalCShar.ServiceConsult.CancelDocumentResponseBody Body;
        
        public CancelDocumentResponse() {
        }
        
        public CancelDocumentResponse(PortalCShar.ServiceConsult.CancelDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class CancelDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelDocumentResult;
        
        public CancelDocumentResponseBody() {
        }
        
        public CancelDocumentResponseBody(string CancelDocumentResult) {
            this.CancelDocumentResult = CancelDocumentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WServiceGetDocumentSoapChannel : PortalCShar.ServiceConsult.WServiceGetDocumentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WServiceGetDocumentSoapClient : System.ServiceModel.ClientBase<PortalCShar.ServiceConsult.WServiceGetDocumentSoap>, PortalCShar.ServiceConsult.WServiceGetDocumentSoap {
        
        public WServiceGetDocumentSoapClient() {
        }
        
        public WServiceGetDocumentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WServiceGetDocumentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceGetDocumentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceGetDocumentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalCShar.ServiceConsult.GetDocumentoPDFResponse PortalCShar.ServiceConsult.WServiceGetDocumentSoap.GetDocumentoPDF(PortalCShar.ServiceConsult.GetDocumentoPDFRequest request) {
            return base.Channel.GetDocumentoPDF(request);
        }
        
        public string GetDocumentoPDF(string NUM_CPE) {
            PortalCShar.ServiceConsult.GetDocumentoPDFRequest inValue = new PortalCShar.ServiceConsult.GetDocumentoPDFRequest();
            inValue.Body = new PortalCShar.ServiceConsult.GetDocumentoPDFRequestBody();
            inValue.Body.NUM_CPE = NUM_CPE;
            PortalCShar.ServiceConsult.GetDocumentoPDFResponse retVal = ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).GetDocumentoPDF(inValue);
            return retVal.Body.GetDocumentoPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetDocumentoPDFResponse> PortalCShar.ServiceConsult.WServiceGetDocumentSoap.GetDocumentoPDFAsync(PortalCShar.ServiceConsult.GetDocumentoPDFRequest request) {
            return base.Channel.GetDocumentoPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetDocumentoPDFResponse> GetDocumentoPDFAsync(string NUM_CPE) {
            PortalCShar.ServiceConsult.GetDocumentoPDFRequest inValue = new PortalCShar.ServiceConsult.GetDocumentoPDFRequest();
            inValue.Body = new PortalCShar.ServiceConsult.GetDocumentoPDFRequestBody();
            inValue.Body.NUM_CPE = NUM_CPE;
            return ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).GetDocumentoPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalCShar.ServiceConsult.GetDocumentoXMLResponse PortalCShar.ServiceConsult.WServiceGetDocumentSoap.GetDocumentoXML(PortalCShar.ServiceConsult.GetDocumentoXMLRequest request) {
            return base.Channel.GetDocumentoXML(request);
        }
        
        public string GetDocumentoXML(string NUM_CPE) {
            PortalCShar.ServiceConsult.GetDocumentoXMLRequest inValue = new PortalCShar.ServiceConsult.GetDocumentoXMLRequest();
            inValue.Body = new PortalCShar.ServiceConsult.GetDocumentoXMLRequestBody();
            inValue.Body.NUM_CPE = NUM_CPE;
            PortalCShar.ServiceConsult.GetDocumentoXMLResponse retVal = ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).GetDocumentoXML(inValue);
            return retVal.Body.GetDocumentoXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetDocumentoXMLResponse> PortalCShar.ServiceConsult.WServiceGetDocumentSoap.GetDocumentoXMLAsync(PortalCShar.ServiceConsult.GetDocumentoXMLRequest request) {
            return base.Channel.GetDocumentoXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetDocumentoXMLResponse> GetDocumentoXMLAsync(string NUM_CPE) {
            PortalCShar.ServiceConsult.GetDocumentoXMLRequest inValue = new PortalCShar.ServiceConsult.GetDocumentoXMLRequest();
            inValue.Body = new PortalCShar.ServiceConsult.GetDocumentoXMLRequestBody();
            inValue.Body.NUM_CPE = NUM_CPE;
            return ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).GetDocumentoXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalCShar.ServiceConsult.GetStatusDocumentResponse PortalCShar.ServiceConsult.WServiceGetDocumentSoap.GetStatusDocument(PortalCShar.ServiceConsult.GetStatusDocumentRequest request) {
            return base.Channel.GetStatusDocument(request);
        }
        
        public string GetStatusDocument(string NUM_CE) {
            PortalCShar.ServiceConsult.GetStatusDocumentRequest inValue = new PortalCShar.ServiceConsult.GetStatusDocumentRequest();
            inValue.Body = new PortalCShar.ServiceConsult.GetStatusDocumentRequestBody();
            inValue.Body.NUM_CE = NUM_CE;
            PortalCShar.ServiceConsult.GetStatusDocumentResponse retVal = ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).GetStatusDocument(inValue);
            return retVal.Body.GetStatusDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetStatusDocumentResponse> PortalCShar.ServiceConsult.WServiceGetDocumentSoap.GetStatusDocumentAsync(PortalCShar.ServiceConsult.GetStatusDocumentRequest request) {
            return base.Channel.GetStatusDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetStatusDocumentResponse> GetStatusDocumentAsync(string NUM_CE) {
            PortalCShar.ServiceConsult.GetStatusDocumentRequest inValue = new PortalCShar.ServiceConsult.GetStatusDocumentRequest();
            inValue.Body = new PortalCShar.ServiceConsult.GetStatusDocumentRequestBody();
            inValue.Body.NUM_CE = NUM_CE;
            return ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).GetStatusDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalCShar.ServiceConsult.GetStatusDocumentsResponse PortalCShar.ServiceConsult.WServiceGetDocumentSoap.GetStatusDocuments(PortalCShar.ServiceConsult.GetStatusDocumentsRequest request) {
            return base.Channel.GetStatusDocuments(request);
        }
        
        public string GetStatusDocuments(string NUM_CE) {
            PortalCShar.ServiceConsult.GetStatusDocumentsRequest inValue = new PortalCShar.ServiceConsult.GetStatusDocumentsRequest();
            inValue.Body = new PortalCShar.ServiceConsult.GetStatusDocumentsRequestBody();
            inValue.Body.NUM_CE = NUM_CE;
            PortalCShar.ServiceConsult.GetStatusDocumentsResponse retVal = ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).GetStatusDocuments(inValue);
            return retVal.Body.GetStatusDocumentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetStatusDocumentsResponse> PortalCShar.ServiceConsult.WServiceGetDocumentSoap.GetStatusDocumentsAsync(PortalCShar.ServiceConsult.GetStatusDocumentsRequest request) {
            return base.Channel.GetStatusDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalCShar.ServiceConsult.GetStatusDocumentsResponse> GetStatusDocumentsAsync(string NUM_CE) {
            PortalCShar.ServiceConsult.GetStatusDocumentsRequest inValue = new PortalCShar.ServiceConsult.GetStatusDocumentsRequest();
            inValue.Body = new PortalCShar.ServiceConsult.GetStatusDocumentsRequestBody();
            inValue.Body.NUM_CE = NUM_CE;
            return ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).GetStatusDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalCShar.ServiceConsult.CancelDocumentResponse PortalCShar.ServiceConsult.WServiceGetDocumentSoap.CancelDocument(PortalCShar.ServiceConsult.CancelDocumentRequest request) {
            return base.Channel.CancelDocument(request);
        }
        
        public string CancelDocument(string param) {
            PortalCShar.ServiceConsult.CancelDocumentRequest inValue = new PortalCShar.ServiceConsult.CancelDocumentRequest();
            inValue.Body = new PortalCShar.ServiceConsult.CancelDocumentRequestBody();
            inValue.Body.param = param;
            PortalCShar.ServiceConsult.CancelDocumentResponse retVal = ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).CancelDocument(inValue);
            return retVal.Body.CancelDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalCShar.ServiceConsult.CancelDocumentResponse> PortalCShar.ServiceConsult.WServiceGetDocumentSoap.CancelDocumentAsync(PortalCShar.ServiceConsult.CancelDocumentRequest request) {
            return base.Channel.CancelDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalCShar.ServiceConsult.CancelDocumentResponse> CancelDocumentAsync(string param) {
            PortalCShar.ServiceConsult.CancelDocumentRequest inValue = new PortalCShar.ServiceConsult.CancelDocumentRequest();
            inValue.Body = new PortalCShar.ServiceConsult.CancelDocumentRequestBody();
            inValue.Body.param = param;
            return ((PortalCShar.ServiceConsult.WServiceGetDocumentSoap)(this)).CancelDocumentAsync(inValue);
        }
    }
}
